# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vicdoblepe/Escritorio/Psico-project/pyqt5-full-app-tutorial-for-beginners-main/Computo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1213, 759)
        Calendar.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.BtnBack = QtWidgets.QPushButton(Calendar)
        self.BtnBack.setGeometry(QtCore.QRect(990, 110, 141, 31))
        self.BtnBack.setObjectName("BtnBack")
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1241, 91))
        self.label.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ComboPekes = QtWidgets.QComboBox(Calendar)
        self.ComboPekes.setGeometry(QtCore.QRect(120, 130, 241, 41))
        self.ComboPekes.setStyleSheet("color: black; \n"
"background: white;\n"
"")
        self.ComboPekes.setEditable(True)
        self.ComboPekes.setObjectName("ComboPekes")
        self.label_2 = QtWidgets.QLabel(Calendar)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 62, 17))
        self.label_2.setStyleSheet("background: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ShowListWidget = QtWidgets.QListWidget(Calendar)
        self.ShowListWidget.setGeometry(QtCore.QRect(690, 160, 491, 421))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(13)
        self.ShowListWidget.setFont(font)
        self.ShowListWidget.setStyleSheet("background:white")
        self.ShowListWidget.setObjectName("ShowListWidget")
        self.BtnShow = QtWidgets.QPushButton(Calendar)
        self.BtnShow.setGeometry(QtCore.QRect(20, 220, 83, 25))
        self.BtnShow.setStyleSheet("background: white;")
        self.BtnShow.setObjectName("BtnShow")
        self.lblcount = QtWidgets.QLabel(Calendar)
        self.lblcount.setGeometry(QtCore.QRect(680, 600, 471, 31))
        self.lblcount.setStyleSheet("font-size:13pt\n"
"")
        self.lblcount.setText("")
        self.lblcount.setObjectName("lblcount")
        self.BtnShowAllToDo = QtWidgets.QPushButton(Calendar)
        self.BtnShowAllToDo.setGeometry(QtCore.QRect(10, 270, 191, 25))
        self.BtnShowAllToDo.setStyleSheet("background: white;")
        self.BtnShowAllToDo.setObjectName("BtnShowAllToDo")
        self.BtnShowScheudeles = QtWidgets.QPushButton(Calendar)
        self.BtnShowScheudeles.setGeometry(QtCore.QRect(10, 320, 191, 25))
        self.BtnShowScheudeles.setStyleSheet("background: white;")
        self.BtnShowScheudeles.setObjectName("BtnShowScheudeles")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Form"))
        self.BtnBack.setText(_translate("Calendar", "Back to Main"))
        self.label.setText(_translate("Calendar", "Computo de horas"))
        self.label_2.setText(_translate("Calendar", "Pekes"))
        self.BtnShow.setText(_translate("Calendar", "Show"))
        self.BtnShowAllToDo.setText(_translate("Calendar", "Show citas por hacer"))
        self.BtnShowScheudeles.setText(_translate("Calendar", "Show citas realizadas"))
