# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vicdoblepe/Escritorio/Psico-project/pyqt5-full-app-tutorial-for-beginners-main/fillprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.bgwidget.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(80, 50, 471, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\"; color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 140, 761, 41))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.signup = QtWidgets.QPushButton(self.bgwidget)
        self.signup.setGeometry(QtCore.QRect(430, 650, 341, 51))
        self.signup.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(170, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.signup.setObjectName("signup")
        self.username = QtWidgets.QLineEdit(self.bgwidget)
        self.username.setGeometry(QtCore.QRect(180, 200, 341, 51))
        self.username.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.username.setText("")
        self.username.setObjectName("username")
        self.firstname = QtWidgets.QLineEdit(self.bgwidget)
        self.firstname.setGeometry(QtCore.QRect(180, 270, 341, 51))
        self.firstname.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.firstname.setObjectName("firstname")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 121, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 81, 20))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(550, 456, 231, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 440, 81, 20))
        self.label_5.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.lastname = QtWidgets.QLineEdit(self.bgwidget)
        self.lastname.setGeometry(QtCore.QRect(180, 430, 341, 51))
        self.lastname.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.lastname.setObjectName("lastname")
        self.birthday = QtWidgets.QDateEdit(self.bgwidget)
        self.birthday.setGeometry(QtCore.QRect(660, 200, 271, 51))
        self.birthday.setStyleSheet("background-color:white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.birthday.setObjectName("birthday")
        self.label_6 = QtWidgets.QLabel(self.bgwidget)
        self.label_6.setGeometry(QtCore.QRect(560, 200, 81, 20))
        self.label_6.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(self.bgwidget)
        self.comboBox.setGeometry(QtCore.QRect(670, 430, 111, 51))
        self.comboBox.setStyleSheet("background-color:white;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_8 = QtWidgets.QLabel(self.bgwidget)
        self.label_8.setGeometry(QtCore.QRect(570, 430, 81, 20))
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.bgwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 350, 81, 20))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.firstname_2 = QtWidgets.QLineEdit(self.bgwidget)
        self.firstname_2.setGeometry(QtCore.QRect(180, 340, 341, 51))
        self.firstname_2.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.firstname_2.setObjectName("firstname_2")
        self.firstname_3 = QtWidgets.QLineEdit(self.bgwidget)
        self.firstname_3.setGeometry(QtCore.QRect(640, 270, 341, 51))
        self.firstname_3.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.firstname_3.setObjectName("firstname_3")
        self.firstname_4 = QtWidgets.QLineEdit(self.bgwidget)
        self.firstname_4.setGeometry(QtCore.QRect(640, 340, 341, 51))
        self.firstname_4.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.firstname_4.setObjectName("firstname_4")
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 280, 81, 20))
        self.label_9.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.bgwidget)
        self.label_10.setGeometry(QtCore.QRect(560, 350, 81, 20))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Fill in your profile"))
        self.label_2.setText(_translate("Dialog", "Now that you\'ve created an account, please fill in your profile."))
        self.signup.setText(_translate("Dialog", "Guardar Niño"))
        self.label_3.setText(_translate("Dialog", "Nombre completo"))
        self.label_4.setText(_translate("Dialog", "Progenitor 1"))
        self.label_5.setText(_translate("Dialog", "Last Name"))
        self.label_6.setText(_translate("Dialog", "Birthday"))
        self.comboBox.setCurrentText(_translate("Dialog", "Público"))
        self.comboBox.setItemText(0, _translate("Dialog", "Público"))
        self.comboBox.setItemText(1, _translate("Dialog", "Privado"))
        self.label_8.setText(_translate("Dialog", "Proviene de"))
        self.label_7.setText(_translate("Dialog", "Progenitor 2"))
        self.label_9.setText(_translate("Dialog", "Teléfono"))
        self.label_10.setText(_translate("Dialog", "Teléfono"))
import placeholder_rc
