# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/victorperez/Escritorio/gui/PAM-GUI/templates/Agenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1126, 710)
        Calendar.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.calendarWidget = QtWidgets.QCalendarWidget(Calendar)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 220, 471, 281))
        self.calendarWidget.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"color:black;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.TaskListWidget = QtWidgets.QListWidget(Calendar)
        self.TaskListWidget.setGeometry(QtCore.QRect(540, 210, 531, 301))
        self.TaskListWidget.setStyleSheet("background:white")
        self.TaskListWidget.setObjectName("TaskListWidget")
        self.BtnBack = QtWidgets.QPushButton(Calendar)
        self.BtnBack.setGeometry(QtCore.QRect(830, 120, 231, 41))
        self.BtnBack.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnBack.setObjectName("BtnBack")
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(-120, 0, 1251, 91))
        self.label.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblFeedback = QtWidgets.QLabel(Calendar)
        self.lblFeedback.setGeometry(QtCore.QRect(40, 640, 621, 71))
        self.lblFeedback.setStyleSheet("Color: green;\n"
"font:12pt;")
        self.lblFeedback.setText("")
        self.lblFeedback.setObjectName("lblFeedback")
        self.saveButton = QtWidgets.QPushButton(Calendar)
        self.saveButton.setGeometry(QtCore.QRect(820, 540, 231, 41))
        self.saveButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.saveButton.setObjectName("saveButton")
        self.SpecialAgenda = QtWidgets.QPushButton(Calendar)
        self.SpecialAgenda.setGeometry(QtCore.QRect(550, 120, 231, 41))
        self.SpecialAgenda.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.SpecialAgenda.setObjectName("SpecialAgenda")
        self.label_2 = QtWidgets.QLabel(Calendar)
        self.label_2.setGeometry(QtCore.QRect(560, 180, 371, 17))
        self.label_2.setObjectName("label_2")
        self.BtnchangeDate = QtWidgets.QPushButton(Calendar)
        self.BtnchangeDate.setGeometry(QtCore.QRect(550, 540, 231, 41))
        self.BtnchangeDate.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnchangeDate.setObjectName("BtnchangeDate")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Form"))
        self.BtnBack.setText(_translate("Calendar", "Back"))
        self.label.setText(_translate("Calendar", "Agenda"))
        self.saveButton.setText(_translate("Calendar", "Guardar cambios"))
        self.SpecialAgenda.setText(_translate("Calendar", "Coordinaciones"))
        self.label_2.setText(_translate("Calendar", "En esta agenda aparecen las citas normales "))
        self.BtnchangeDate.setText(_translate("Calendar", "Moodificar cita"))
