# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/victorperez/Escritorio/Aplicaciones/PAM-GUI/templates/Createkid.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1111, 715)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 1120, 715))
        self.bgwidget.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.bgwidget.setObjectName("bgwidget")
        self.lbl_subHeader = QtWidgets.QLabel(self.bgwidget)
        self.lbl_subHeader.setGeometry(QtCore.QRect(80, 140, 761, 41))
        self.lbl_subHeader.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.lbl_subHeader.setObjectName("lbl_subHeader")
        self.savekid = QtWidgets.QPushButton(self.bgwidget)
        self.savekid.setGeometry(QtCore.QRect(350, 590, 341, 51))
        self.savekid.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.savekid.setObjectName("savekid")
        self.nombrefield = QtWidgets.QLineEdit(self.bgwidget)
        self.nombrefield.setGeometry(QtCore.QRect(180, 200, 371, 41))
        self.nombrefield.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.nombrefield.setText("")
        self.nombrefield.setObjectName("nombrefield")
        self.progenitor1field = QtWidgets.QLineEdit(self.bgwidget)
        self.progenitor1field.setGeometry(QtCore.QRect(180, 270, 371, 41))
        self.progenitor1field.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.progenitor1field.setObjectName("progenitor1field")
        self.lbl_nombre = QtWidgets.QLabel(self.bgwidget)
        self.lbl_nombre.setGeometry(QtCore.QRect(40, 210, 121, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_progenitor1 = QtWidgets.QLabel(self.bgwidget)
        self.lbl_progenitor1.setGeometry(QtCore.QRect(50, 280, 81, 20))
        self.lbl_progenitor1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_progenitor1.setObjectName("lbl_progenitor1")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(460, 520, 231, 20))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color:red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.lbl_email = QtWidgets.QLabel(self.bgwidget)
        self.lbl_email.setGeometry(QtCore.QRect(70, 420, 51, 20))
        self.lbl_email.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_email.setObjectName("lbl_email")
        self.emailfield = QtWidgets.QLineEdit(self.bgwidget)
        self.emailfield.setGeometry(QtCore.QRect(170, 410, 371, 41))
        self.emailfield.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.emailfield.setObjectName("emailfield")
        self.lbl_origen = QtWidgets.QLabel(self.bgwidget)
        self.lbl_origen.setGeometry(QtCore.QRect(570, 210, 81, 20))
        self.lbl_origen.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_origen.setObjectName("lbl_origen")
        self.lbl_progenitor2 = QtWidgets.QLabel(self.bgwidget)
        self.lbl_progenitor2.setGeometry(QtCore.QRect(50, 350, 81, 20))
        self.lbl_progenitor2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_progenitor2.setObjectName("lbl_progenitor2")
        self.progenitor2field = QtWidgets.QLineEdit(self.bgwidget)
        self.progenitor2field.setGeometry(QtCore.QRect(180, 340, 371, 41))
        self.progenitor2field.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.progenitor2field.setObjectName("progenitor2field")
        self.tfn1field = QtWidgets.QLineEdit(self.bgwidget)
        self.tfn1field.setGeometry(QtCore.QRect(640, 270, 371, 41))
        self.tfn1field.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tfn1field.setObjectName("tfn1field")
        self.tfn2field = QtWidgets.QLineEdit(self.bgwidget)
        self.tfn2field.setGeometry(QtCore.QRect(640, 340, 371, 41))
        self.tfn2field.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tfn2field.setObjectName("tfn2field")
        self.lbl_tfn_1 = QtWidgets.QLabel(self.bgwidget)
        self.lbl_tfn_1.setGeometry(QtCore.QRect(570, 280, 61, 21))
        self.lbl_tfn_1.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_tfn_1.setObjectName("lbl_tfn_1")
        self.lbl_tfn_2 = QtWidgets.QLabel(self.bgwidget)
        self.lbl_tfn_2.setGeometry(QtCore.QRect(570, 350, 61, 21))
        self.lbl_tfn_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_tfn_2.setObjectName("lbl_tfn_2")
        self.back = QtWidgets.QPushButton(self.bgwidget)
        self.back.setGeometry(QtCore.QRect(920, 100, 141, 61))
        self.back.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.back.setObjectName("back")
        self.lbl_header = QtWidgets.QLabel(self.bgwidget)
        self.lbl_header.setGeometry(QtCore.QRect(0, 0, 1120, 91))
        self.lbl_header.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.lbl_header.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_header.setObjectName("lbl_header")
        self.comboPublic = QtWidgets.QComboBox(self.bgwidget)
        self.comboPublic.setGeometry(QtCore.QRect(660, 190, 241, 41))
        self.comboPublic.setStyleSheet("color: black; \n"
"background: white;\n"
"")
        self.comboPublic.setEditable(True)
        self.comboPublic.setObjectName("comboPublic")
        self.lbl_h_asignadas = QtWidgets.QLabel(self.bgwidget)
        self.lbl_h_asignadas.setGeometry(QtCore.QRect(560, 420, 151, 21))
        self.lbl_h_asignadas.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lbl_h_asignadas.setObjectName("lbl_h_asignadas")
        self.asignacionfield = QtWidgets.QLineEdit(self.bgwidget)
        self.asignacionfield.setGeometry(QtCore.QRect(720, 410, 251, 41))
        self.asignacionfield.setStyleSheet("background-color:white;\n"
"border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.asignacionfield.setObjectName("asignacionfield")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_subHeader.setText(_translate("Dialog", "Rellena los datos, por favor"))
        self.savekid.setText(_translate("Dialog", "Guardar Niño en la BD"))
        self.lbl_nombre.setText(_translate("Dialog", "Nombre completo"))
        self.lbl_progenitor1.setText(_translate("Dialog", "Progenitor 1"))
        self.lbl_email.setText(_translate("Dialog", "Email"))
        self.lbl_origen.setText(_translate("Dialog", "Proviene de"))
        self.lbl_progenitor2.setText(_translate("Dialog", "Progenitor 2"))
        self.lbl_tfn_1.setText(_translate("Dialog", "Teléfono"))
        self.lbl_tfn_2.setText(_translate("Dialog", "Teléfono"))
        self.back.setText(_translate("Dialog", "Back"))
        self.lbl_header.setText(_translate("Dialog", "Introduce los datos"))
        self.lbl_h_asignadas.setText(_translate("Dialog", "Nº de horas asignadas"))
