# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/victorperez/Escritorio/gui/PAM-GUI/templates/QCalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1120, 715)
        Calendar.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.calendarWidget = QtWidgets.QCalendarWidget(Calendar)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 120, 551, 341))
        self.calendarWidget.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"color:black;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.timefield = QtWidgets.QTimeEdit(Calendar)
        self.timefield.setGeometry(QtCore.QRect(40, 610, 221, 41))
        self.timefield.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"")
        self.timefield.setObjectName("timefield")
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(0, -10, 1120, 91))
        self.label.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblFeedback = QtWidgets.QLabel(Calendar)
        self.lblFeedback.setGeometry(QtCore.QRect(620, 260, 461, 71))
        self.lblFeedback.setStyleSheet("Color: green;\n"
"font:12pt;")
        self.lblFeedback.setText("")
        self.lblFeedback.setObjectName("lblFeedback")
        self.ComboPekes = QtWidgets.QComboBox(Calendar)
        self.ComboPekes.setEnabled(True)
        self.ComboPekes.setGeometry(QtCore.QRect(630, 120, 201, 25))
        self.ComboPekes.setStyleSheet("color: black; \n"
"background: white;\n"
"")
        self.ComboPekes.setEditable(True)
        self.ComboPekes.setObjectName("ComboPekes")
        self.BtnAddSpecialDate = QtWidgets.QPushButton(Calendar)
        self.BtnAddSpecialDate.setGeometry(QtCore.QRect(570, 600, 231, 41))
        self.BtnAddSpecialDate.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.BtnAddSpecialDate.setObjectName("BtnAddSpecialDate")
        self.BtnBack = QtWidgets.QPushButton(Calendar)
        self.BtnBack.setGeometry(QtCore.QRect(870, 110, 231, 41))
        self.BtnBack.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnBack.setObjectName("BtnBack")
        self.BtnAddNew = QtWidgets.QPushButton(Calendar)
        self.BtnAddNew.setGeometry(QtCore.QRect(840, 600, 231, 41))
        self.BtnAddNew.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnAddNew.setObjectName("BtnAddNew")
        self.label_4 = QtWidgets.QLabel(Calendar)
        self.label_4.setGeometry(QtCore.QRect(30, 550, 241, 41))
        self.label_4.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Form"))
        self.label.setText(_translate("Calendar", "Preprarar cita"))
        self.BtnAddSpecialDate.setText(_translate("Calendar", "Añadir Coordinación"))
        self.BtnBack.setText(_translate("Calendar", "Back to Main"))
        self.BtnAddNew.setText(_translate("Calendar", "Añadir Cita"))
        self.label_4.setText(_translate("Calendar", "Introduce formato de 24h"))
