# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/victorperez/Escritorio/gui/PAM-GUI/templates/QCalendarSpecialDate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1120, 715)
        Calendar.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.calendarWidget = QtWidgets.QCalendarWidget(Calendar)
        self.calendarWidget.setGeometry(QtCore.QRect(20, 180, 501, 361))
        self.calendarWidget.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"color:black;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.timefield = QtWidgets.QTimeEdit(Calendar)
        self.timefield.setGeometry(QtCore.QRect(50, 630, 231, 41))
        self.timefield.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"")
        self.timefield.setObjectName("timefield")
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1141, 91))
        self.label.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblFeedback = QtWidgets.QLabel(Calendar)
        self.lblFeedback.setGeometry(QtCore.QRect(430, 560, 741, 151))
        self.lblFeedback.setStyleSheet("Color: green;\n"
"font:12pt;")
        self.lblFeedback.setText("")
        self.lblFeedback.setObjectName("lblFeedback")
        self.SpecialDateDesc = QtWidgets.QLineEdit(Calendar)
        self.SpecialDateDesc.setGeometry(QtCore.QRect(550, 180, 541, 371))
        self.SpecialDateDesc.setStyleSheet("background: white;")
        self.SpecialDateDesc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SpecialDateDesc.setObjectName("SpecialDateDesc")
        self.label_2 = QtWidgets.QLabel(Calendar)
        self.label_2.setGeometry(QtCore.QRect(550, 130, 271, 41))
        self.label_2.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.BtnBack = QtWidgets.QPushButton(Calendar)
        self.BtnBack.setGeometry(QtCore.QRect(950, 100, 141, 61))
        self.BtnBack.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnBack.setObjectName("BtnBack")
        self.BtnAddSpecialDate = QtWidgets.QPushButton(Calendar)
        self.BtnAddSpecialDate.setGeometry(QtCore.QRect(800, 630, 231, 41))
        self.BtnAddSpecialDate.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnAddSpecialDate.setObjectName("BtnAddSpecialDate")
        self.label_4 = QtWidgets.QLabel(Calendar)
        self.label_4.setGeometry(QtCore.QRect(40, 580, 241, 41))
        self.label_4.setStyleSheet("background: white;\n"
"border-radius: 20px;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Form"))
        self.label.setText(_translate("Calendar", "Preparar coordinación"))
        self.label_2.setText(_translate("Calendar", "Describe brevemente la cita"))
        self.BtnBack.setText(_translate("Calendar", "Back"))
        self.BtnAddSpecialDate.setText(_translate("Calendar", "Añadir Coordinación"))
        self.label_4.setText(_translate("Calendar", "Introduce formato de 24h"))
