# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/victorperez/Escritorio/gui/PAM-GUI/templates/Special_Agenda.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar(object):
    def setupUi(self, Calendar):
        Calendar.setObjectName("Calendar")
        Calendar.resize(1120, 715)
        Calendar.setStyleSheet("background-color:rgb(144, 158, 184);")
        self.calendarWidget = QtWidgets.QCalendarWidget(Calendar)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 220, 471, 261))
        self.calendarWidget.setStyleSheet("background:white;\n"
"font: 13pt;\n"
"color:black;")
        self.calendarWidget.setObjectName("calendarWidget")
        self.TaskListWidget = QtWidgets.QListWidget(Calendar)
        self.TaskListWidget.setGeometry(QtCore.QRect(570, 220, 521, 271))
        self.TaskListWidget.setStyleSheet("background:white")
        self.TaskListWidget.setObjectName("TaskListWidget")
        self.label = QtWidgets.QLabel(Calendar)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1131, 91))
        self.label.setStyleSheet("\n"
"color:white;\n"
"font-size: 32px;\n"
"background: #01BFFF;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lblFeedback = QtWidgets.QLabel(Calendar)
        self.lblFeedback.setGeometry(QtCore.QRect(40, 640, 621, 71))
        self.lblFeedback.setStyleSheet("Color: green;\n"
"font:12pt;")
        self.lblFeedback.setText("")
        self.lblFeedback.setObjectName("lblFeedback")
        self.label_2 = QtWidgets.QLabel(Calendar)
        self.label_2.setGeometry(QtCore.QRect(560, 180, 351, 17))
        self.label_2.setObjectName("label_2")
        self.BtnBack = QtWidgets.QPushButton(Calendar)
        self.BtnBack.setGeometry(QtCore.QRect(940, 100, 141, 61))
        self.BtnBack.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.BtnBack.setObjectName("BtnBack")
        self.saveButton = QtWidgets.QPushButton(Calendar)
        self.saveButton.setGeometry(QtCore.QRect(840, 550, 231, 41))
        self.saveButton.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(214, 234, 248);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.saveButton.setObjectName("saveButton")

        self.retranslateUi(Calendar)
        QtCore.QMetaObject.connectSlotsByName(Calendar)

    def retranslateUi(self, Calendar):
        _translate = QtCore.QCoreApplication.translate
        Calendar.setWindowTitle(_translate("Calendar", "Form"))
        self.label.setText(_translate("Calendar", " Agenda Especial"))
        self.label_2.setText(_translate("Calendar", "En esta agenda aparecen las coordinaciones "))
        self.BtnBack.setText(_translate("Calendar", "Back"))
        self.saveButton.setText(_translate("Calendar", "Añadir Cita"))
